use_frameworks!

platform :ios, '10.0'

target 'WhatsappStatusRingBar_Example' do
  pod 'WhatsappStatusRingBar', :path => '../'

  target 'WhatsappStatusRingBar_Tests' do
    inherit! :search_paths

    
  end
end
